### ISSUE TITLE
手动安装运行出现错误 TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by z1137254268** [krau/aria2bot#5]
Traceback (most recent call last):
  File "bot.py", line 11, in <module>
    from 源码.小工具 import 仅主人装饰器, 开始标记
  File "/aria2bot/源码/小工具.py", line 21, in <module>
    async def 从消息中获取链接列表(文字消息: str) -> list[str | None]:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by krau** [comment]
无法复现, 但是尝试了进行修复, 请拉取最新仓库并重试

**Comment by z1137254268** [comment]
拉取最新仓库 运行出现 Traceback (most recent call last):
  File "bot.py", line 11, in <module>
    from 源码.小工具 import 仅主人装饰器, 开始标记
  File "/aria2bot/源码/小工具.py", line 21, in <module>
    async def 从消息中获取链接列表(文字消息: str) -> list[str]:
TypeError: 'type' object is not subscriptable  
![image](https://user-images.githubusercontent.com/51695259/236217485-0a23b414-d058-4449-9a23-59a0dc37c893.png)

**Comment by krau** [comment]
> 

你的Python版本是什么?

**Comment by z1137254268** [comment]
![image](https://user-images.githubusercontent.com/51695259/236219455-2178f471-e007-454b-9cb3-094dfb2856d8.png)

**Comment by krau** [comment]
> ![image](https://user-images.githubusercontent.com/51695259/236219455-2178f471-e007-454b-9cb3-094dfb2856d8.png)

这是由低版本与最新版本Python的类型注解系统的差异导致的错误, 已尝试修复.
推荐使用最新版本(3.11.3)版本Python

**Comment by z1137254268** [comment]
测试后可行 但运行后下面代码也出现了错误提示 能否为以下的全部代码也进行兼容配置 
![image](https://user-images.githubusercontent.com/51695259/236233633-10566a53-43e6-4bd0-9874-694717b3647f.png)

**Comment by krau** [comment]
> 测试后可行 但运行后下面代码也出现了错误提示 能否为以下的全部代码也进行兼容配置 ![image](https://user-images.githubusercontent.com/51695259/236233633-10566a53-43e6-4bd0-9874-694717b3647f.png)

已经修改, 如果仍有类似问题欢迎继续反馈

**Comment by z1137254268** [comment]
![image](https://user-images.githubusercontent.com/51695259/236251569-fe688c96-7dd6-408b-aa1d-8cdf76e580e9.png)

**Comment by z1137254268** [comment]
试着将 68 行的 object | None 替换为  [object, None] 进行运行 运行成功后 进入telegram机器人 输入/start 出现错误 
![I6ZS@`M1EV_H(MZR8%1KZ K](https://user-images.githubusercontent.com/51695259/236262687-aee09368-1680-40d7-81d8-f03e37fc7dc2.png)

**Comment by krau** [comment]
> 试着将 68 行的 object | None 替换为 [object, None] 进行运行 运行成功后 进入telegram机器人 输入/start 出现错误 ![I6ZS@`M1EV_H(MZR8%1KZ K](https://user-images.githubusercontent.com/51695259/236262687-aee09368-1680-40d7-81d8-f03e37fc7dc2.png)

在我相同python版本下没能复现, 重新拉取仓库并重装依赖试下?

**Comment by z1137254268** [comment]
重新拉取仓库 重装依赖 运行后还是一样。。

**Comment by krau** [comment]
> 重新拉取仓库 重装依赖 运行后还是一样。。

删除原先的文件夹重新拉取, 另外检查下你的配置文件是否按照正确的 yaml 格式填写了
